-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: Create core_program_hafta table for decoupled weekly live sessions
-- Geleceğin Dijital Sağlık Liderleri - WEEKLY-PROGRAM-MODULE-01
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.core_program_hafta (
  id bigint generated by default as identity primary key,
  hafta integer not null unique,
  baslik text not null,
  hedef text null,
  aktif boolean not null default false,
  sali_aktif boolean not null default true,
  persembe_aktif boolean not null default true,
  sali_zoom_url text null,
  sali_calendar_url text null,
  sali_meeting_id text null,
  sali_passcode text null,
  persembe_zoom_url text null,
  persembe_calendar_url text null,
  persembe_meeting_id text null,
  persembe_passcode text null,
  guncellenme_tarihi timestamptz null,
  olusturulma_tarihi timestamptz not null default now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_program_hafta_hafta ON public.core_program_hafta(hafta);
CREATE INDEX IF NOT EXISTS idx_program_hafta_aktif ON public.core_program_hafta(aktif);

-- Enable RLS
ALTER TABLE public.core_program_hafta ENABLE ROW LEVEL SECURITY;

-- Drop existing policies for idempotency
DROP POLICY IF EXISTS "Public and authenticated can view active program weeks" ON public.core_program_hafta;
DROP POLICY IF EXISTS "Admins can view all program weeks" ON public.core_program_hafta;
DROP POLICY IF EXISTS "Admins can manage program weeks" ON public.core_program_hafta;
DROP POLICY IF EXISTS "Allow select active program weeks for all" ON public.core_program_hafta;
DROP POLICY IF EXISTS "Allow all for authenticated admins" ON public.core_program_hafta;

-- Katılımcılar ve herkes sadece aktif haftaları okuyabilir
CREATE POLICY "Allow select active program weeks for all"
ON public.core_program_hafta
FOR SELECT
TO authenticated, anon
USING (aktif = true);

-- Adminler tüm haftaları okuyabilir ve yönetebilir
CREATE POLICY "Allow all for authenticated admins"
ON public.core_program_hafta
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Seed 3 Weeks Idempotently
INSERT INTO public.core_program_hafta (
  hafta,
  baslik,
  hedef,
  aktif,
  sali_aktif,
  persembe_aktif,
  sali_zoom_url,
  sali_calendar_url,
  sali_meeting_id,
  sali_passcode,
  persembe_zoom_url,
  persembe_calendar_url,
  persembe_meeting_id,
  persembe_passcode
)
VALUES
(
  1,
  'Hedef Kitleyi Tanıma ve Temel İnşası',
  'Katılımcının içerik üretmeye başlamadan önce hedef kitlesini tanıması, davranışların altındaki kök nedenleri anlaması ve aynı sağlık bilgisini, özellikle antibiyotik direncini, farklı kitlelere uyarlayabilmesidir.',
  false,
  true,
  true,
  'https://us06web.zoom.us/j/89490424441?pwd=t3edWpY1m0Vh37kg9I7AsV0nyll1nP.1',
  'https://us06web.zoom.us/meeting/tZ0pfumsrD8uHtUo3YmaRUGtvjRbabuDiGT6/ics?icsToken=DGEu-nEGL9lk-0t6SAAALAAAAKeEbH7SUK7pA9n6NqViJmw2dxqO3xbOjJ5QtLRvx5btCFOfYK5LVn8Q9ayNm7XpvhT6ovT-QG1BK0jQ8DAwMDAwMg&meetingMasterEventId=BmN668jBQsClNpVfaeI5FA',
  '894 9042 4441',
  '028359',
  'https://us06web.zoom.us/j/82503028748?pwd=tFq1DRiTRRP0NhXtR4tRbb5akbeQh6.1',
  'https://us06web.zoom.us/meeting/tZYod-qorDMtHtzzqHwbZr2npVRPFj35VvdH/ics?icsToken=DIrwF6pseC-HkaBijgAALAAAAENRjQhmZPyBHQIRw8tiRuKCJymxuIe4URp3AwAxkMkOLwQ7zG50BRXIrIiCDvW9nBBjYLgKXMFFJoUPtTAwMDAwMg&meetingMasterEventId=rNVKAcW4T3uK3iSqgflUhA',
  '825 0302 8748',
  '386049'
),
(
  2,
  'Bilgiyi Derinleştirme ve Dijital Araçlar',
  'Katılımcının bilimsel kaynakları okuyup değerlendirebilmesini, sağlık bilgisini yanlış bilgiden ayırabilmesini ve kendi seçtiği doğru bilgiyi sosyal medya ve yapay zekâ araçlarıyla etkili bir içeriğe dönüştürebilmesini sağlamak.',
  false,
  true,
  true,
  'https://us06web.zoom.us/j/89490424441?pwd=t3edWpY1m0Vh37kg9I7AsV0nyll1nP.1',
  'https://us06web.zoom.us/meeting/tZ0pfumsrD8uHtUo3YmaRUGtvjRbabuDiGT6/ics?icsToken=DGEu-nEGL9lk-0t6SAAALAAAAKeEbH7SUK7pA9n6NqViJmw2dxqO3xbOjJ5QtLRvx5btCFOfYK5LVn8Q9ayNm7XpvhT6ovT-QG1BK0jQ8DAwMDAwMg&meetingMasterEventId=BmN668jBQsClNpVfaeI5FA',
  '894 9042 4441',
  '028359',
  'https://us06web.zoom.us/j/82503028748?pwd=tFq1DRiTRRP0NhXtR4tRbb5akbeQh6.1',
  'https://us06web.zoom.us/meeting/tZYod-qorDMtHtzzqHwbZr2npVRPFj35VvdH/ics?icsToken=DIrwF6pseC-HkaBijgAALAAAAENRjQhmZPyBHQIRw8tiRuKCJymxuIe4URp3AwAxkMkOLwQ7zG50BRXIrIiCDvW9nBBjYLgKXMFFJoUPtTAwMDAwMg&meetingMasterEventId=rNVKAcW4T3uK3iSqgflUhA',
  '825 0302 8748',
  '386049'
),
(
  3,
  'Sahne, İtibar ve Kriz Yönetimi',
  'Katılımcının ikinci haftada hazırladığı bilimsel içeriği kamera önünde doğal ve güven veren biçimde sunabilmesini; içerik yayınlandıktan sonra ortaya çıkabilecek eleştiri, yanlış bilgi ve dijital itibar sorunlarını profesyonel biçimde yönetebilmesini ve içerik üretimini sürdürülebilir bir çalışma düzenine dönüştürmesini sağlamak.',
  false,
  true,
  true,
  'https://us06web.zoom.us/j/89490424441?pwd=t3edWpY1m0Vh37kg9I7AsV0nyll1nP.1',
  'https://us06web.zoom.us/meeting/tZ0pfumsrD8uHtUo3YmaRUGtvjRbabuDiGT6/ics?icsToken=DGEu-nEGL9lk-0t6SAAALAAAAKeEbH7SUK7pA9n6NqViJmw2dxqO3xbOjJ5QtLRvx5btCFOfYK5LVn8Q9ayNm7XpvhT6ovT-QG1BK0jQ8DAwMDAwMg&meetingMasterEventId=BmN668jBQsClNpVfaeI5FA',
  '894 9042 4441',
  '028359',
  'https://us06web.zoom.us/j/82503028748?pwd=tFq1DRiTRRP0NhXtR4tRbb5akbeQh6.1',
  'https://us06web.zoom.us/meeting/tZYod-qorDMtHtzzqHwbZr2npVRPFj35VvdH/ics?icsToken=DIrwF6pseC-HkaBijgAALAAAAENRjQhmZPyBHQIRw8tiRuKCJymxuIe4URp3AwAxkMkOLwQ7zG50BRXIrIiCDvW9nBBjYLgKXMFFJoUPtTAwMDAwMg&meetingMasterEventId=rNVKAcW4T3uK3iSqgflUhA',
  '825 0302 8748',
  '386049'
)
ON CONFLICT (hafta) DO UPDATE SET
  baslik = EXCLUDED.baslik,
  hedef = EXCLUDED.hedef,
  sali_zoom_url = COALESCE(public.core_program_hafta.sali_zoom_url, EXCLUDED.sali_zoom_url),
  sali_calendar_url = COALESCE(public.core_program_hafta.sali_calendar_url, EXCLUDED.sali_calendar_url),
  sali_meeting_id = COALESCE(public.core_program_hafta.sali_meeting_id, EXCLUDED.sali_meeting_id),
  sali_passcode = COALESCE(public.core_program_hafta.sali_passcode, EXCLUDED.sali_passcode),
  persembe_zoom_url = COALESCE(public.core_program_hafta.persembe_zoom_url, EXCLUDED.persembe_zoom_url),
  persembe_calendar_url = COALESCE(public.core_program_hafta.persembe_calendar_url, EXCLUDED.persembe_calendar_url),
  persembe_meeting_id = COALESCE(public.core_program_hafta.persembe_meeting_id, EXCLUDED.persembe_meeting_id),
  persembe_passcode = COALESCE(public.core_program_hafta.persembe_passcode, EXCLUDED.persembe_passcode);

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
