-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: Participant Activity & Login Tracking (PARTICIPANT-ACTIVITY-TRACKING-01)
-- Geleceğin Dijital Sağlık Liderleri (GDSL)
-- Tarih: 2026-08-17
-- Amaç: Katılımcıların sisteme giriş ve aktivite durumlarını güvenli ve KVKK
--        uyumlu şekilde takip etmek için veri modeli, indeksler, RLS ve RPC fonksiyonu.
-- Kural: İdempotent — tekrar çalıştırılabilir.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. core_katilimci tablosuna aktivite takip kolonları ekle
ALTER TABLE public.core_katilimci
  ADD COLUMN IF NOT EXISTS ilk_giris_tarihi timestamptz NULL,
  ADD COLUMN IF NOT EXISTS son_giris_tarihi timestamptz NULL,
  ADD COLUMN IF NOT EXISTS son_aktivite_tarihi timestamptz NULL,
  ADD COLUMN IF NOT EXISTS giris_sayisi integer NOT NULL DEFAULT 0;

-- 2. Detaylı aktivite ve oturum log tablosu
CREATE TABLE IF NOT EXISTS public.core_katilimci_oturumlog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  katilimci_id bigint NOT NULL REFERENCES public.core_katilimci(id) ON DELETE CASCADE,
  user_id uuid NULL,
  event_type text NOT NULL,
  user_agent text NULL,
  path text NULL,
  olusturulma_tarihi timestamptz NOT NULL DEFAULT now()
);

-- 3. İndeksler (Sorgu ve raporlama performansı için)
CREATE INDEX IF NOT EXISTS idx_oturumlog_katilimci_id 
  ON public.core_katilimci_oturumlog(katilimci_id);

CREATE INDEX IF NOT EXISTS idx_oturumlog_event_type 
  ON public.core_katilimci_oturumlog(event_type);

CREATE INDEX IF NOT EXISTS idx_oturumlog_olusturulma_tarihi 
  ON public.core_katilimci_oturumlog(olusturulma_tarihi DESC);

CREATE INDEX IF NOT EXISTS idx_oturumlog_katilimci_tarih 
  ON public.core_katilimci_oturumlog(katilimci_id, olusturulma_tarihi DESC);

-- 4. RLS Etkinleştirme & Güvenlik Politikaları
ALTER TABLE public.core_katilimci_oturumlog ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SEC02 Admin Oturum Loglarini Yonetir" ON public.core_katilimci_oturumlog;
CREATE POLICY "SEC02 Admin Oturum Loglarini Yonetir"
ON public.core_katilimci_oturumlog FOR ALL
USING (
  public.is_admin()
)
WITH CHECK (
  public.is_admin()
);

DROP POLICY IF EXISTS "SEC02 Katilimci Kendi Oturum Loglarini Gorur" ON public.core_katilimci_oturumlog;
CREATE POLICY "SEC02 Katilimci Kendi Oturum Loglarini Gorur"
ON public.core_katilimci_oturumlog FOR SELECT
USING (
  katilimci_id = public.current_katilimci_id()
);

DROP POLICY IF EXISTS "SEC02 Katilimci Kendi Oturum Logunu Ekler" ON public.core_katilimci_oturumlog;
CREATE POLICY "SEC02 Katilimci Kendi Oturum Logunu Ekler"
ON public.core_katilimci_oturumlog FOR INSERT
WITH CHECK (
  katilimci_id = public.current_katilimci_id()
);

-- 5. Güvenli RPC Fonksiyonu: record_participant_activity
-- Hassas kolonlar (giris_sayisi, son_giris_tarihi vs.) client tarafından doğrudan
-- update edilmez, SECURITY DEFINER yetkili fonksiyon ile atomik olarak güncellenir.
CREATE OR REPLACE FUNCTION public.record_participant_activity(
  p_event_type text,
  p_path text DEFAULT NULL,
  p_user_agent text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_role text;
  v_katilimci_id bigint;
  v_now timestamptz := now();
BEGIN
  -- 1. Oturum kontrolü
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Aktif oturum bulunamadı');
  END IF;

  -- 2. Profiles tablosundan rol ve core_katilimci_id kontrolü
  SELECT role, core_katilimci_id INTO v_role, v_katilimci_id
  FROM public.profiles
  WHERE id = v_user_id;

  -- Katılımcı olmayanlar (admin, mentor vb.) için sessizce atla
  IF LOWER(COALESCE(v_role, '')) != 'katilimci' OR v_katilimci_id IS NULL THEN
    RETURN jsonb_build_object('ok', true, 'skipped', true, 'reason', 'Not a participant');
  END IF;

  -- 3. Oturum log kaydı ekle
  INSERT INTO public.core_katilimci_oturumlog (
    katilimci_id,
    user_id,
    event_type,
    path,
    user_agent,
    olusturulma_tarihi
  ) VALUES (
    v_katilimci_id,
    v_user_id,
    COALESCE(p_event_type, 'activity_ping'),
    p_path,
    p_user_agent,
    v_now
  );

  -- 4. core_katilimci özet alanlarını güncelle
  IF p_event_type IN ('login', 'password_recovery_login') THEN
    UPDATE public.core_katilimci
    SET
      son_aktivite_tarihi = v_now,
      son_giris_tarihi = v_now,
      ilk_giris_tarihi = COALESCE(ilk_giris_tarihi, v_now),
      giris_sayisi = COALESCE(giris_sayisi, 0) + 1
    WHERE id = v_katilimci_id;
  ELSE
    UPDATE public.core_katilimci
    SET son_aktivite_tarihi = v_now
    WHERE id = v_katilimci_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'katilimci_id', v_katilimci_id,
    'event_type', p_event_type,
    'recorded_at', v_now
  );
END;
$$;

-- Authenticated kullanıcılara RPC çalıştırma yetkisi ver
GRANT EXECUTE ON FUNCTION public.record_participant_activity(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_participant_activity(text, text, text) TO anon;

-- PostgREST şema önbelleğini tazele
NOTIFY pgrst, 'reload schema';
