-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: Create core_mentornotu table for private mentor notes
-- Geleceğin Dijital Sağlık Liderleri - MENTOR-ACTIVE-PANEL-01
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.core_mentornotu (
  id bigint generated by default as identity primary key,
  mentor_id bigint not null references public.core_mentor(id) on delete cascade,
  katilimci_id bigint not null references public.core_katilimci(id) on delete cascade,
  not_metni text not null,
  kategori text null default 'Genel',
  onem_derecesi text null default 'Normal',
  olusturulma_tarihi timestamptz not null default now(),
  guncellenme_tarihi timestamptz null
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_mentornotu_mentor_id ON public.core_mentornotu(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentornotu_katilimci_id ON public.core_mentornotu(katilimci_id);
CREATE INDEX IF NOT EXISTS idx_mentornotu_mentor_katilimci ON public.core_mentornotu(mentor_id, katilimci_id);

-- Enable RLS
ALTER TABLE public.core_mentornotu ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any to ensure idempotency
DROP POLICY IF EXISTS "Mentors can manage their own notes" ON public.core_mentornotu;
DROP POLICY IF EXISTS "Admins can manage all mentor notes" ON public.core_mentornotu;

-- Mentor policy: only own notes via profiles.core_mentor_id
CREATE POLICY "Mentors can manage their own notes"
ON public.core_mentornotu
FOR ALL
TO authenticated
USING (
  mentor_id IN (
    SELECT core_mentor_id FROM public.profiles WHERE id = auth.uid() AND core_mentor_id IS NOT NULL
  )
)
WITH CHECK (
  mentor_id IN (
    SELECT core_mentor_id FROM public.profiles WHERE id = auth.uid() AND core_mentor_id IS NOT NULL
  )
);

-- Admin policy: full access for admins
CREATE POLICY "Admins can manage all mentor notes"
ON public.core_mentornotu
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
